export const defaultFormData = {
  projectName: '',
  domain: 'Web App',
  analysisMode: 'Full Product',
  description: '',
  teamSize: 3,
  teamExperience: 'Beginner',
  timelineDays: 30,
  modules: 5,
  features: 8,
  integrations: 2,
  userRoles: 2,
  platform: 'Web',
  uiComplexity: 'Medium',
  dataComplexity: 'Medium',
  securityLevel: 'Medium',
  scalabilityNeed: 'Medium',
  hasAuth: true,
  hasPayments: false,
  hasRealtime: false,
  hasAI: false,
  hasAnalytics: false,
  hasFileUpload: false,
  uncertaintyLevel: 'Medium',
  externalDependencyLevel: 'Medium'
};
